# Alacritty terminal emulator configuration
#
# Windows:
#   $APPDATA/alacritty/alacritty.toml

[general]
live_config_reload = true

[terminal]
shell = { program = "C:/Users/corey.goldberg/Scoop/apps/git/current/bin/bash.exe", args = ["--login"] }

[window]
dimensions = { columns = 180, lines = 40 }
padding = { x = 0, y = 0 }
position = { x = 0, y = 0 }

[font]
size = 10

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 500
blink_timeout = 0

[keyboard]
bindings = [
    { key = "V", mods = "Control", action = "Paste" },
]
